// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Document struct {
	ID        uuid.UUID       `json:"id"`
	Title     string          `json:"title"`
	OwnerID   uuid.NullUUID   `json:"owner_id"`
	Content   sql.NullString  `json:"content"`
	CreatedAt sql.NullTime    `json:"created_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
}

type DocumentPermission struct {
	UserID     uuid.UUID       `json:"user_id"`
	DocumentID uuid.UUID       `json:"document_d"`
	Permission sql.NullString  `json:"permission"`
}

type User struct {
	ID           uuid.UUID     `json:"id"`
	Email        string        `json:"email"`
	PasswordHash string        `json:"hashed_password"`
	CreatedAt    sql.NullTime  `json:"created_at"`
}


