// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Document struct {
	ID        uuid.UUID
	Title     string
	OwnerID   uuid.NullUUID
	Content   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type DocumentPermission struct {
	UserID     uuid.UUID
	DocumentID uuid.UUID
	Permission sql.NullString
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
}
